<?php 
/**
 * ZF2 Buch Kapitel 2
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 2.4 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 2.4</h1>
<h3>Beispiel für eine Closure Definition mit übergebenen Variablen</h3>
<pre>
&lt;?php 
$basePrice = 3.95;
$itemPrice = 0.95;

$pizzaPrice = function($items) use ($basePrice, $itemPrice) {
    return $basePrice + $items * $itemPrice;
};

echo $pizzaPrice(2) . "&lt;br /&gt;";  // output 5.85
echo $pizzaPrice(6) . "&lt;br /&gt;";  // output 9.65
</pre>
<h3>Ausgabe</h3>
<pre>
<?php 
$basePrice = 3.95;
$itemPrice = 0.95;

$pizzaPrice = function($items) use ($basePrice, $itemPrice) {
    return $basePrice + $items * $itemPrice;
};

echo $pizzaPrice(2) . "<br />";  // output 5.85
echo $pizzaPrice(6) . "<br />";  // output 9.65
?>
</pre>
</div>
</div>
