<?php 
/**
 * ZF2 Buch Kapitel 2
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 2.3 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 2.3</h1>
<h3>Beispiel für eine einfache Closure Definition</h3>
<pre>
&lt;?php 
$pizzaPrice = function($items) {
    return 3.95 + $items * 0.95;
};

echo $pizzaPrice(3) . "&lt;br /&gt;";  // output 6.8
echo $pizzaPrice(7) . "&lt;br /&gt;";  // output 10.6
</pre>
<h3>Ausgabe</h3>
<pre>
<?php 
$pizzaPrice = function($items) {
    return 3.95 + $items * 0.95;
};

echo $pizzaPrice(3) . "<br />";  // output 6.8
echo $pizzaPrice(7) . "<br />";  // output 10.6
?>
</pre>
</div>
</div>
