<?php 
/**
 * ZF2 Buch Kapitel 2
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 2</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing0201">Listing 2.1</a></td>
<td>Namensraum Deklaration für Config Klasse</td>
</tr>
<tr>
<td><a href="/listing/listing0202">Listing 2.2</a></td>
<td>Namensraum Deklaration für einen Action-Controller</td>
</tr>
<tr>
<td><a href="/listing/listing0203">Listing 2.3</a></td>
<td>Beispiel für eine einfache Closure Definition</td>
</tr>
<tr>
<td><a href="/listing/listing0204">Listing 2.4</a></td>
<td>Beispiel für eine Closure Definition mit übergebenen Variablen</td>
</tr>
<tr>
<td><a href="/listing/listing0205">Listing 2.5</a></td>
<td>Beispiel für eine Closure Definition als Parameter einer Funktion</td>
</tr>
<tr>
<td><a href="/listing/listing0206">Listing 2.6</a></td>
<td>Beispiel für Late Static Binding</td>
</tr>
<tr>
<td><a href="/listing/listing0207">Listing 2.7</a></td>
<td>Klasse für eine Pizza Salami mit festen Belägen und Pizzaboden</td>
</tr>
<tr>
<td><a href="/listing/listing0208">Listing 2.8</a></td>
<td>Klasse für Pizza mit variablen Belägen und Pizzaboden</td>
</tr>
<tr>
<td><a href="/listing/listing0209">Listing 2.9</a></td>
<td>Einfache Implementierung eines Service-Locators</td>
</tr>
<tr>
<td><a href="/listing/listing0210">Listing 2.10</a></td>
<td>Implementation eines Service-Locators mit Closures</td>
</tr>
<tr>
<td><a href="/listing/listing0211">Listing 2.11</a></td>
<td>Beispiel für einen Event-Manager</td>
</tr>
</tbody>
</table>
